<?php

return [
    'card'=>[
        'names'=>[
            'joker',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'T',
            'J',
            'Q',
            'K',
            'A'
        ],
        'suits'=>[
            'S',
            'D',
            'C',
            'H'
        ]
    ],
    'combos'=>[
        'straightFlush',
        'fourOfKind',
        'fullHouse',
        'flush',
        'straight',
        'threeOfKind',
        'twoPairs',
        'onePair',
        'highCard'
    ]

];
