<?php

return [
    'card'=>[
        'names'=>[
            'joker',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            'j',
            'q',
            'k',
            'a'
        ],
        'suits'=>[
            's',
            'd',
            'c',
            'h'
        ]
    ],
    'combos'=>[
        'straightFlush',
        'fourOfKind',
        'fullHouse',
        'flush',
        'straight',
        'threeOfKind',
        'twoPairs',
        'onePair',
        'highCard'
    ]

];
